name: MtxFrame
version: '${project.version}'
main: at.mtxframe.mtxframe.MtxFrame
api-version: '1.20'
load: POSTWORLD
author: MeteryX
depend:
  - Vault

commands:
  itemtest:
    usage: /itemtest
    aliases:
      - citem
